variable "publicsubnet" {}
variable "privatesubnet" {}
variable "datasubnet" {}
variable "region" {}
variable "cidr" {}
variable "ami" {}
variable "type" {}
variable "az" {}
variable "type_ubuntu" {}
variable "ami_ubuntu" {}
variable "type_small" {}
